/* Minimal site-wide Goodreads config.
   The shelf snapshots are generated by GitHub Actions into goodreads/shelves/*.json. */

window.GOODREADS_SITE_CONFIG = {
    userId: '98490343',
    userSlug: 'jonatan',
    profileSlug: '98490343-jonatan',
    shelves: ['currently-reading', 'to-read', 'read'],
    displayNames: {
        'currently-reading': 'Currently reading',
        'to-read': 'Want to read',
        'read': 'Read'
    }
};

